### ISSUE TITLE
Code wont compile

### ISSUE THREAD

**Issue by gustaveherbst** [Opentrons/SmoothiewareABC#1]
Code errors out on a "make clean all"

Compiling modules/robot/Feedback.cpp
modules/robot/Feedback.cpp:17:33: fatal error: modules/robot/robot.h: No such file or directory
 #include "modules/robot/robot.h"

Looks like modules directory is incomplete

**Comment by nwags** [comment]
Haven't looked at this code in a bit, but was meaning to soon to clean up a few things. Will check it out tonight or tomorrow.

**Comment by gustaveherbst** [comment]
Found the issue, in src/modules/robot/Feedback.cpp the robot.h reference should be Robot.h, changing this allowed the code to compile fully with no errors. Please make this change, checkin the code so at the very least this compiles all the way through. Thanks

**Comment by nwags** [comment]
As mentioned in my email to you, there will be a number of changes made in the near future and the issue will be addressed then.
